#!/bin/bash

alias romd='cd ~/${ROM}'
alias dtd='romd;cd device/xiaomi/jason'
alias kd='romd; cd kernel/xiaomi/jason'
alias vnd='romd; cd vendor/xiaomi/jason'
alias home='cd ~/'
alias syncrepo='repo sync -f --force-sync --no-tags --no-clone-bundle'

alias javatwrp='sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64'
alias javarom='sudo update-java-alternatives --set /usr/lib/jvm/java-8-oracle'

RED='\033[0;31m'
NC='\033[0m'

function formatota() {
echo -e "${RED}NAME:${NC}";
stat -c %n $1 | sed 's/.*\///';
echo -e "${RED}SIZE:${NC}";
cat $1 | wc -c;
echo -e "${RED}TIMESTAMP:${NC}";
stat -c %Y $1;
echo -e "${RED}SHA256SUM:${NC}";
sha256sum $1 | cut -d " " -f 1;
}

function buildrom() {
echo "ROM specified is ${ROM}";
cd ~/${ROM};
source build/envsetup.sh;
if [ ${ROM} == "aicp" ]
then
time brunch aicp_jason-userdebug;
elif [ ${ROM} == "aosip" ]
then
lunch aosip_jason-userdebug;
time mka kronic;
elif [ ${ROM} == "crdroid" ]
then
time brunch lineage_jason-userdebug;
fi
}

function buildbi() {
echo "Building bootimage for ${ROM}";
cd ~/${ROM};
source build/envsetup.sh;
if [ ${ROM} == "aicp" ]
then
lunch aicp_jason-userdebug;
make -j16 bootimage;
elif [ ${ROM} == "aosip" ]
then
lunch aosip_jason-userdebug;
time mka bootimage;
elif [ ${ROM} == "crdroid" ]
then
lunch lineage_jason-userdebug;
make -j16 bootimage;
fi
}
