#!/bin/bash

alias romd='cd ~/${ROM}'
alias dtd='romd;cd device/xiaomi/jason'
alias kd='romd; cd kernel/xiaomi/jason'
alias vnd='romd; cd vendor/xiaomi/jason'
alias home='cd ~/'
alias syncrepo='repo sync -f --force-sync --no-tags --no-clone-bundle'
alias logg='git log --pretty=short'
alias cls='clear;clear;clear'

alias javatwrp='sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64'
alias javarom='sudo update-java-alternatives --set /usr/lib/jvm/java-8-oracle'

RED='\033[0;31m'
NC='\033[0m'

function formatota() {
echo -e "${RED}NAME:${NC}";
stat -c %n $1 | sed 's/.*\///';
echo -e "${RED}SIZE:${NC}";
cat $1 | wc -c;
echo -e "${RED}TIMESTAMP:${NC}";
stat -c %Y $1;
echo -e "${RED}SHA256SUM:${NC}";
sha256sum $1 | cut -d " " -f 1;
}

function buildrom() {
echo "ROM specified is ${ROM}";
cd ~/${ROM};
source build/envsetup.sh;
if [ ${ROM} == "aicp" ]
then
time brunch aicp_jason-userdebug;
elif [ ${ROM} == "aosip" ]
then
lunch aosip_jason-userdebug;
time mka kronic;
elif [ ${ROM} == "crdroid" ]
then
time brunch lineage_jason-userdebug;
fi
}

function buildbi() {
echo "Building bootimage for ${ROM}";
cd ~/${ROM};
source build/envsetup.sh;
if [ ${ROM} == "aicp" ]
then
lunch aicp_jason-userdebug;
make -j16 bootimage;
elif [ ${ROM} == "aosip" ]
then
lunch aosip_jason-userdebug;
time mka bootimage;
elif [ ${ROM} == "crdroid" ]
then
lunch lineage_jason-userdebug;
make -j16 bootimage;
fi
}

function pushrit() {
echo "Username: uvera";
echo "Project: AOSIP/$1";
echo "Branch pie";
git push ssh://uvera@review.aosiprom.com:29418/AOSIP/"$1" HEAD:refs/for/pie;
}

function sdm660_add_wifi() {
git remote add caf/qcacld-3.0 https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/ && git fetch caf/qcacld-3.0 wlan-cld3.driver.lnx.1.1.r41-rel && git merge -s ours --no-commit caf/qcacld-3.0/wlan-cld3.driver.lnx.1.1.r41-rel && git read-tree --prefix=drivers/staging/qcacld-3.0 -u caf/qcacld-3.0/wlan-cld3.driver.lnx.1.1.r41-rel && git commit --no-edit;
git remote add caf/qca-wifi-host-cmn https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn/ && git fetch caf/qca-wifi-host-cmn wlan-cmn.driver.lnx.1.0.r41-rel && git merge -s ours --no-commit caf/qca-wifi-host-cmn/wlan-cmn.driver.lnx.1.0.r41-rel && git read-tree --prefix=drivers/staging/qca-wifi-host-cmn -u caf/qca-wifi-host-cmn/wlan-cmn.driver.lnx.1.0.r41-rel && git commit --no-edit;
git remote add caf/fw-api https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api/ && git fetch caf/fw-api wlan-api.lnx.1.1.r45-rel && git merge -s ours --no-commit caf/fw-api/wlan-api.lnx.1.1.r45-rel && git read-tree --prefix=drivers/staging/fw-api -u caf/fw-api/wlan-api.lnx.1.1.r45-rel && git commit --no-edit;
}

alias pick='git cherry-pick -s';

function abort() {
if [ $1 == "c" ]
then
git cherry-pick --abort
elif [ $1 == "r" ]
then
git revert --abort
elif [ $1 == "m" ]
then
git merge --abort
elif [ $1 == "a" ]
then
git am --abort
fi
}
