#!/bin/bash

alias romd='cd ~/${ROM}'
alias dtd='romd;cd device/xiaomi/jason'
alias kd='romd; cd kernel/xiaomi/jason'
alias vnd='romd; cd vendor/xiaomi/jason'
alias home='cd ~/'
alias syncrepo='repo sync -f --force-sync --no-tags --no-clone-bundle'

alias javatwrp='sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64'
alias javarom='sudo update-java-alternatives --set /usr/lib/jvm/java-8-oracle'

alias buildrom='. build/envsetup.sh; lunch ${ROM}_jason-userdebug; time mka $1'
RED='\033[0;31m'
NC='\033[0m'

function formatota() {
echo -e "${RED}NAME:${NC}";
stat -c %n $1 | sed 's/.*\///';
echo -e "${RED}SIZE:${NC}";
cat $1 | wc -c;
echo -e "${RED}TIMESTAMP:${NC}";
stat -c %Y $1;
echo -e "${RED}SHA256SUM:${NC}";
sha256sum $1 | cut -d " " -f 1;
}
